version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        # Set this to the server ip/domain, if your backend is deployed on a different server
        #VITE_BACKEND_URL: http://123.123.123.123:5000
        VITE_STREAM_DELAY: 18
        VITE_STREAM_PROXY_DELAY: 30
        # Optional settings for synchronization
        #VITE_SYNCHRONIZATION_TOLERANCE: 0.8
        #VITE_SYNCHRONIZATION_MAX_DEVIATION: 4
        #VITE_SYNCHRONIZATION_ADJUSTMENT: 0.06
        #VITE_SYNCHRONIZATION_MAX_ADJUSTMENT: 0.16

    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - streams_data:/streams
    environment:
      DEFAULT_CHANNEL_URL: https://mcdn.daserste.de/daserste/de/master.m3u8
      STORAGE_PATH: /streams/
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
      - streams_data:/streams
    networks:
      - app-network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      # Nginx Proxy Manager Web - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

# Volumes
volumes:
  streams_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

# Internal docker network
networks:
  app-network:
    driver: bridge